APPLICATION = vrvm-node

BOARD ?= iotlab-m3

RIOTBASE ?=$(CURDIR)/../RIOT

# Utilities
USEMODULE += ztimer_msec
USEMODULE += shell
USEMODULE += shell_cmds_default

# Sensors
USEMODULE += lps331ap

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include